#!/bin/bash

mkdir -p ../bin
mkdir -p ../out

if [ $# -eq 0 ]; then
    FILE_NAME="../examples/default.htpl"
    echo -e "No filename provided. Using default file: $FILE_NAME\n"
else
    FILE_NAME="$1"
fi


LEX_FILE="../src/lexer.l"
LEX_OUTPUT="../out/lexer.c"
LEX_HEADER="../out/lexer.h"

BISON_FILE="../src/parser.y"
BISON_OUTPUT="../out/parser.c"
BISON_HEADER="../out/parser.h"

LIBRARIES="../src/symbols_table.c ../src/syntax_tree.c"

BINARY_PROGRAM="../bin/compiler"


./clean
set -e

bison -Wcounterexamples -d -o "$BISON_OUTPUT" --defines="$BISON_HEADER" "$BISON_FILE"
flex --header-file="$LEX_HEADER" -o "$LEX_OUTPUT" "$LEX_FILE"
gcc -o "$BINARY_PROGRAM" "$BISON_OUTPUT" "$LEX_OUTPUT" $LIBRARIES -lfl -lm -I"../src" -I"../out"
"$BINARY_PROGRAM" "$FILE_NAME"