#!/bin/bash

mkdir -p ../bin
mkdir -p ../out

if [ $# -eq 0 ]; then
    FILE_NAME="../examples/default.htpl"
    echo -e "No filename provided. Using default file: $FILE_NAME\n"
else
    FILE_NAME="$1"
fi

LEX_FILE="../src/main.l"
LEX_OUTPUT="../out/lex.yy.c"
BINARY_PROGRAM="../bin/prog"
LIBRARIES="../src/symbols_table.c"

flex -o "$LEX_OUTPUT" "$LEX_FILE"
gcc -o "$BINARY_PROGRAM" "$LEX_OUTPUT" "$LIBRARIES" -lfl -I"../src" -I"../out"
"$BINARY_PROGRAM" "$FILE_NAME"
